
server:
  port: 8090


spring:
  application:
    name: exchange-center
  datasource:
    url: jdbc:mysql://localhost:3306/db?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123

dubbo:
  scan:
    base-packages: com.github.zibuyu28.exchange.service
  protocol:
    name: dubbo
    port: 32345
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
  application:
    qosEnable: true
    qosPort: 42222
    qosAcceptForeignIp: true
    qos-enable-compatible: true
    qos-host-compatible: localhost
    qos-port-compatible: 42222
    qos-accept-foreign-ip-compatible: true
    qos-host: localhost
