server:
  port: 8089

spring:
  application:
    name: rmb-center
  datasource:
    url: jdbc:mysql://localhost:3306/db?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123

mybatis:
  type-aliases-package: com.github.zibuyu28.rmbcenter.mapper

dubbo:
  scan:
    base-packages: com.github.zibuyu28.rmbcenter.service
  protocol:
    name: dubbo
    port: 22345
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
  application:
    qosEnable: true
    qosPort: 32222
    qosAcceptForeignIp: true
    qos-enable-compatible: true
    qos-host-compatible: localhost
    qos-port-compatible: 32222
    qos-accept-foreign-ip-compatible: true
    qos-host: localhost